#!/bin/sh -e

kiss-macros configure \
    --without-selinux \
    --with-privsep-user=nobody \
    --with-mantype=doc \
    --without-rpath \
    --disable-strip \
    --with-ssl-engine \
    --with-pid-dir=/run \
    --disable-wtmp \
    --disable-utmp

make
make DESTDIR="$1" install

install -m 755 contrib/ssh-copy-id   "$1/pkg/$3/exec/ssh-copy-id"
install -m 644 contrib/ssh-copy-id.1 "$1/pkg/$3/man/man8/ssh-copy-id.1"
