#!/bin/sh -e

# Setup base directories.
for d in boot dev conf home mnt bulk opt run; do
    install -dm 755 "$1/$d"
done

install -dm 555  "$1/proc"
install -dm 555  "$1/sys"
install -dm 0750 "$1/home/root"
install -dm 1777 "$1/tmp"

# Setup /bulk.
for d in cache local opt log/old lib/misc empty service; do
    install -dm 755 "$1/bulk/$d"
done

install -dm 1777 "$1/bulk/tmp"
install -dm 1777 "$1/bulk/spool/mail"

ln -s spool/mail  "$1/bulk/mail"
ln -s ../run      "$1/bulk/run"
ln -s ../run/lock "$1/bulk/lock"

# /conf skeleton files.
for f in fstab group host.conf hosts issue os-release \
         passwd profile securetty shells mime.types; do
    install -m 644 "$f" "$1/conf"
done

for f in crypttab shadow; do
    install -m 600 "$f" "$1/conf"
done

ln -s /proc/self/mounts "$1/conf/mtab"
