#!/bin/sh -e

export DESTDIR="$1"

# Don't build tests.
sed -i "/subdir('tests')/d" meson.build

kiss-macros meson \
    -Ddocs=false \
    -Dintrospection=false \
    . output

ninja -C output
ninja -C output install
