#!/bin/sh -e

sed -i '/chown/d' bsd.prog.mk

./configure \
    --prefix="/pkg/$3" \
    --bindir="/pkg/$3/exec" \
    --sysconfdir=/conf \
    --mandir="/pkg/$3/man" \
    --enable-static \
    --with-shadow \
    --with-timestamp \
    --without-pam

make
make DESTDIR="$1" install

install -Dm600 doas.conf "$1/conf/doas.conf"
