#!/bin/sh -e

kiss-macros configure \
    --enable-libuuid \
    --enable-libblkid \
    --enable-fsck \
    --disable-makeinstall-chown \
    --disable-rpath \
    --without-udev \
    --without-python \
    --without-systemd

make
make DESTDIR="$1" install

# Fix broken --sbindir.
mv -f "$1/pkg/$3/sbin/"* "$1/pkg/$3/exec"
rmdir "$1/pkg/$3/sbin"

# Fix broken --bindir...
mv -f "$1/pkg/$3/bin/"* "$1/pkg/$3/exec"
rmdir "$1/pkg/$3/bin"
