#!/bin/sh -e

export DESTDIR="$1"
export LDFLAGS="$LDFLAGS -Wl,-z,lazy"

kiss-macros meson \
    -Ddefault-dri=3 \
    -Dxvmc=false \
    -Dvalgrind=false \
    . build

ninja -C build
ninja -C build install
