#!/bin/sh -e

ln -s waf-2.0.18 waf

python waf configure \
    --prefix="/pkg/$3" \
    --bindir="/pkg/$3/exec" \
    --mandir="/pkg/$3/man" \
    --confdir=/conf/mpv \
    --datadir="/pkg/$3/data" \
    --docdir="/pkg/$3/doc" \
    --enable-alsa \
    --enable-libass

python waf build
python waf install --destdir="$1"
