#!/bin/sh -e

for patch in *.patch; do
    patch -p1 < "$patch"
done

# Build and install regular busybox.
# This excludes utilities which require 'suid' to function.
make CC="${CC:-cc}" HOSTCC="${CC:-cc}"
make CONFIG_PREFIX="$1/pkg/$3/exec" install

# Rename the binary temporarily.
mv "$1/pkg/$3/exec/busybox" "$1/pkg/$3/exec/busybox-nosuid"

# Build and install suid busybox.
# This _only_ includes utlities which require 'suid' to function.
cp -f .config-suid .config
make CC="${CC:-cc}" HOSTCC="${CC:-cc}"
make CONFIG_PREFIX="$1/usr" install

# Aptly name the busybox binaries.
mv -f "$1/pkg/$3/exec/busybox"        "$1/pkg/$3/exec/busybox-suid"
mv -f "$1/pkg/$3/exec/busybox-nosuid" "$1/pkg/$3/exec/busybox"

# Install the non-suid symlinks.
"$1/pkg/$3/exec/busybox" --list | while read -r bin; do
    ln -s busybox "$1/pkg/$3/exec/$bin"
done

# Install the suid symlinks.
"$1/pkg/$3/exec/busybox-suid" --list | while read -r bin; do
    ln -s busybox-suid "$1/pkg/$3/exec/$bin"
done

# Set suid on busybox suid.
chmod u+s "$1/pkg/$3/exec/busybox-suid"

# The acpid command requires that this directory exist
# and does not automatically create it..
mkdir -p "$1/conf/acpid"

# Install runit services.
install -Dm755 acpid.run           "$1/conf/sv/acpid/run"
install -Dm755 crond.run           "$1/conf/sv/crond/run"
install -Dm755 syslogd.run         "$1/conf/sv/syslogd/run"
install -Dm755 mdev.run            "$1/conf/sv/mdev/run"
install -Dm755 ntpd.run            "$1/conf/sv/ntpd/run"
ln -s /run/runit/supervise.acpid   "$1/conf/sv/acpid/supervise"
ln -s /run/runit/supervise.crond   "$1/conf/sv/crond/supervise"
ln -s /run/runit/supervise.syslogd "$1/conf/sv/syslogd/supervise"
ln -s /run/runit/supervise.mdev    "$1/conf/sv/mdev/supervise"
ln -s /run/runit/supervise.ntpd    "$1/conf/sv/ntpd/supervise"

install -Dm644 mdev.conf "$1/conf/mdev.conf"
