#!/bin/sh -e

cat > makeinfo <<EOF
#!/bin/sh
printf 'makeinfo (GNU texinfo) 5.2\n'
EOF

chmod +x makeinfo
export PATH=$PATH:$PWD

kiss-macros configure \
    --enable-targets=x86_64-pep \
    --enable-gold \
    --enable-lto \
    --enable-ld=default \
    --enable-plugins \
    --disable-multilib \
    --disable-werror \
    --disable-gdb \
    --disable-nls \
    --disable-readline \
    --disable-gprof \
    --with-mmap \
    --with-system-zlib

make configure-host
make tooldir="/pkg/$3"
make DESTDIR="$1" prefix="/pkg/$3" tooldir="/pkg/$3" install
