#!/bin/sh -e

pkg_dir=$1

make CC="${CC:-cc}"
make DESTDIR="$1" \
    USRDIR="/pkg/$3" \
    USRSHAREDIR="/pkg/$3/data" \
    ZICDIR="/pkg/$3/exec" \
    TZDEFAULT=/conf/localtime \
    BINDIR="/pkg/$3/exec" \
    MANDIR="/pkg/$3/man" \
    install

set -- africa asia australasia europe northamerica southamerica

./zic -d "$pkg_dir/pkg/$3/data/zoneinfo" "$@"
./zic -d "$pkg_dir/pkg/$3/data/zoneinfo/posix" "$@"
./zic -d "$pkg_dir/pkg/$3/data/zoneinfo/right" -L leapseconds "$@"
./zic -d "$pkg_dir/pkg/$3/data/zoneinfo" -p America/New_York

mv "$pkg_dir/pkg/australasia/data/"* "$pkg_dir/pkg/$3/data"
rm -rf "$pkg_dir/pkg/australasia/"
