#!/bin/sh -e

patch -p1 < mandoc-no-warn.patch

sed -i '/int dummy/d'         compat_err.c
sed -i 's,"more -s","less",g' main.c
sed -i "s/CC=.*/CC='$CC'/"    configure

cat > configure.local <<EOF
PREFIX=/pkg/$3
MANDIR=/pkg/$3/man
LIBDIR=/pkg/$3/lib
SBINDIR=/pkg/$3/exec
BINDIR=/pkg/$3/exec
CC="${CC:-cc}"
CFLAGS="$CFLAGS"
LN="ln -sf"
EOF

./configure

make
make -j1 DESTDIR="$1" base-install
