#!/bin/sh -e

kiss-macros configure \
    --syslibdir="/pkg/$3/lib"

make
make DESTDIR="$1" install

mkdir -p "$1/pkg/$3/exec"
ln -s  "/pkg/$3/lib/ld-musl-x86_64.so.1" "$1/pkg/$3/exec/ldd"

# Fix incorrect symlink to libc.so.
ln -sf libc.so "$1/pkg/$3/lib/ld-musl-x86_64.so.1"

# Install BSD compatibility headers.
install -Dm 755 cdefs.h "$1/pkg/$3/inc/sys/cdefs.h"
install -Dm 755 queue.h "$1/pkg/$3/inc/sys/queue.h"
install -Dm 755 tree.h  "$1/pkg/$3/inc/sys/tree.h"

# Install getconf.
cc getconf.c -o "$1/pkg/$3/exec/getconf"
cc getent.c  -o "$1/pkg/$3/exec/getent"
