#!/bin/sh -e

make CC="${CC:-cc} -static"

install -Dm755 pigz   "$1/pkg/$3/exec/pigz"
install -Dm755 unpigz "$1/pkg/$3/exec/unpigz"
install -Dm644 pigz.1 "$1/pkg/$3/man/man1/pigz.1"

ln -sf pigz   "$1/pkg/$3/exec/gzip"
ln -sf pigz   "$1/pkg/$3/exec/zcat"
ln -sf unpigz "$1/pkg/$3/exec/gunzip"
ln -sf pigz.1 "$1/pkg/$3/man/man1/gzip.1"
