#!/bin/sh -e

export LDFLAGS="$LDFLAGS -static"

kiss-macros configure \
    --enable-symlink-install \
    --enable-libuuid \
    --enable-libblkid \
    --disable-nls \
    --disable-uuidd \
    --disable-fsck \
    --disable-elf-shlibs \
    --with-udev-rules-dir=/conf/udev/rules.d

# MKDIR_P fixes an install issue on musl/busybox.
make
make MKDIR_P="install -d" DESTDIR="$1" install

# Our e2fsprogs build uses the private libblkid
# and libuuid libraries which ship with it.
#
# It is then built statically which allows us to
# remove the libraries entirely.
#
# This is all done to remove the util-linux
# dependency from this package.
#
# The build system doesn't provide a target
# for this so we must do it ourselves.
rm -rf \
    "$1/pkg/$3/exec/blkid" \
    "$1/pkg/$3/exec/uuidgen" \
    "$1/pkg/$3/exec/findfs" \
    "$1/pkg/$3/man/man8/findfs.8" \
    "$1/pkg/$3/man/man8/blkid.8" \
    "$1/pkg/$3/man/man3/libblkid.3" \
    "$1/pkg/$3/man/man3/"uuid* \
    "$1/pkg/$3/man/man1/uuidgen.1" \
    "$1/pkg/$3/lib/pkgconfig/uuid.pc" \
    "$1/pkg/$3/lib/pkgconfig/blkid.pc" \
    "$1/pkg/$3/lib/libuuid.a" \
    "$1/pkg/$3/lib/libblkid.a" \
    "$1/pkg/$3/inc/blkid" \
    "$1/pkg/$3/inc/uuid"
