#!/bin/sh -e

# Thanks for using nonstandard directives, ffmpeg. Really loving it.
./configure \
    --prefix="/pkg/$3" \
    --bindir="/pkg/$3/exec" \
    --datadir="/pkg/$3/data" \
    --docdir="/pkg/$3/doc" \
    --libdir="/pkg/$3/lib" \
    --shlibdir="/pkg/$3/lib" \
    --incdir="/pkg/$3/inc" \
    --mandir="/pkg/$3/man" \
    --cc="${CC:-cc}" \
    --cxx="${CXX:-c++}" \
    --enable-shared \
    --enable-gpl \
    --enable-version3 \
    --enable-nonfree \
    --enable-openssl \
    --enable-libass \
    --enable-libmp3lame \
    --enable-libopus \
    --enable-libvorbis \
    --enable-libvpx \
    --enable-libx264 \
    --enable-libx265 \
    --enable-libxvid \
    --enable-libwebp \
    --enable-libdrm \
    --x86asmexe=nasm \
    --disable-debug \
    --disable-libxml2

make
make DESTDIR="$1" install

rm -rf "$1/pkg/$3/data/examples"
