#!/bin/sh -e

export DESTDIR="$1"

pkg-config --exists libudev || {
    printf 'eudev (or libudev-zero) is required\n'
    exit 1
}

kiss-macros meson \
    -Ddebug-gui=false \
    -Ddocumentation=false \
    -Dtests=false \
    -Dlibwacom=false \
    -Dudev="${udev:=true}" \
    . output

ninja -C output
ninja -C output install
