#!/bin/sh -e

CFLAGS_FOR_BUILD=-fPIC \
kiss-macros configure \
    --without-xmlto \
    --disable-specs \
    --enable-static

make
make DESTDIR="$1" install

# This will be removed once 'xorgproto' 2019.2
# is released.
rm -f "$1/pkg/$3/inc/X11/extensions/XKBgeom.h"
