#!/bin/sh -e

for patch in *.patch; do
    patch -p1 < "$patch"
done

# Avoid repeating ourselves.
mk() {
    make \
        libdir="/pkg/$3/lib" \
        bindir="/pkg/$3/exec" \
        mandir="/pkg/$3/man"  \
        includedir="/pkg/$3/inc" \
        "$@"
}

mk CC="${CC:-cc}"
mk DESTDIR="$1" install
