#!/bin/sh -e

kiss-macros configure

make

install -Dm 755 ccache       "$1/pkg/$3/exec/ccache"
install -Dm 644 doc/ccache.1 "$1/pkg/$3/man/man1/ccache.1"

mkdir -p "$1/usr/lib/ccache/bin"

host=$(cc -dumpmachine)

for link in cc gcc g++ cpp c++ \
            "$host-cc" "$host-gcc" "$host-g++" "$host-cpp" "$host-c++"; do
    ln -sf /usr/bin/ccache "$1/usr/lib/ccache/bin/$link"
done
