#!/bin/sh -e

# Remove incorrect bash dependency.
sed -i 's/bash/sh/' install-sh

kiss-macros configure \
    --disable-gettext

make
make \
    DIST_ROOT="$1" \
    PKG_ROOT_SBIN_DIR="/pkg/$3/exec" \
    PKG_ROOT_BIN_DIR="/pkg/$3/exec" \
    PKG_ROOT_LIB_DIR="/pkg/$3/lib" \
    install
