#!/bin/sh -e

kiss-macros configure \
    --with-udev-rules-dir=/conf/udev/rules.d \
    --disable-alsaconf \
    --disable-bat \
    --disable-xmlto \
    --disable-nls

make
make DESTDIR="$1" install
