#!/bin/sh -e

export BUILD_ZLIB=0
export BUILD_BZIP2=0
export LDFLAGS="$LDFLAGS -pthread"
export CFLAGS="$CFLAGS -DNO_POSIX_2008_LOCALE -D_GNU_SOURCE"

./Configure \
    -des \
    -Dprefix="/pkg/$3" \
    -Dvendorprefix="/pkg/$3" \
    -Dman1dir="/pkg/$3/man/man1" \
    -Dman3dir="/pkg/$3/man/man3" \
    -Dbin="/pkg/$3/exec" \
    -Dscriptdir="/pkg/$3/exec" \
    -Dusevendorprefix \
    -Duseshrplib \
    -Dusesoname \
    -Dusethreads \
    -Dinc_version_list=none \
    -Dd_sockaddr_in6=define \
    -Dcccdlflags=-fPIC \
    -Dccflags="$CFLAGS" \
    -Dlddlflags="-shared $LDFLAGS" \
    -Dldflags="$LDFLAGS" \
    -Doptimize="-Wall $CFLAGS" \
    -Dcc="${CC:-cc}" \
    -Dar="${AR:-ar}" \
    -Dnm="${NM:-nm}" \
    -Dranlib="${RANLIB:-ranlib}" \
    -Dperl_static_inline="static __inline__" \
    -Dd_static_inline

sh
make
make DESTDIR="$1" install

# Remove all unneeded files.
find "$1" -name \*.pod       -exec rm -f {} +
find "$1" -name .packlist    -exec rm -f {} +
find "$1" -name README\*     -exec rm -f {} +
find "$1" -name TODO\*       -exec rm -f {} +
find "$1" -name Change\*     -exec rm -f {} +
find "$1" -name \*.bs        -exec rm -f {} +
find "$1" -name \*.0 -type f -exec rm -f {} +

# Fix permissions.
find "$1/pkg/$3/lib" -type f -exec chmod 644 {} \;
#xmv "$1/pkg/$3/bin" "$1/pkg/$3/exec"
